# Generated by Django 4.1.7 on 2023-02-25 20:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.datetime_safe


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("projects", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Comment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", models.CharField(max_length=280)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("file", models.FileField(blank=True, upload_to="")),
                ("image", models.ImageField(blank=True, upload_to="")),
            ],
        ),
        migrations.CreateModel(
            name="Like",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Post",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("summary", models.CharField(max_length=280)),
                ("detail", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("UPDT", "Update"),
                            ("LESL", "Lesson Learned"),
                            ("CHNG", "Change Request"),
                            ("QUES", "Question"),
                            ("EVNT", "Event"),
                            ("THNK", "Thanks"),
                            ("RISK", "Risk"),
                            ("INFO", "Information"),
                        ],
                        max_length=4,
                    ),
                ),
                ("files", models.FileField(blank=True, upload_to="")),
                ("image", models.ImageField(blank=True, upload_to="")),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.RenameField(
            model_name="project", old_name="is_completed", new_name="is_archived",
        ),
        migrations.RenameField(
            model_name="project", old_name="name", new_name="title",
        ),
        migrations.RemoveField(model_name="project", name="end_date",),
        migrations.AddField(
            model_name="project", name="purpose", field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="project",
            name="sponsor",
            field=models.ManyToManyField(
                related_name="sponsored_projects", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="status",
            field=models.CharField(
                choices=[
                    ("100", "Pending"),
                    ("200", "On Track"),
                    ("300", "Off Track"),
                    ("400", "At Risk"),
                    ("500", "Hold"),
                    ("600", "Completed"),
                ],
                default="100",
                max_length=3,
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="success_criteria",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="project",
            name="start_date",
            field=models.DateField(default=django.utils.datetime_safe.date.today),
        ),
        migrations.DeleteModel(name="Update",),
        migrations.AddField(
            model_name="post",
            name="project",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="updates",
                to="projects.project",
            ),
        ),
        migrations.AddField(
            model_name="like",
            name="post",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="projects.post"
            ),
        ),
        migrations.AddField(
            model_name="like",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="comment",
            name="post",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="projects.post"
            ),
        ),
        migrations.AddField(
            model_name="comment",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
