# Generated by Django 4.1.7 on 2023-03-04 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0003_alter_post_image_alter_project_assigned_to_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="files",
            field=models.FileField(blank=True, upload_to="files/"),
        ),
    ]
